### ISSUE TITLE
runtime: out of memory: cannot allocate 8192-byte block (1664319488 in use) fatal error: out of memory

### ISSUE THREAD

**Issue by yadu-boss** [yadu-boss/Praveesh#1]
runtime: out of memory: cannot allocate 8192-byte block (1664319488 in use)
fatal error: out of memory

goroutine 34 [running]:
runtime.throw(0x12ae662, 0xd)
        C:/go/src/runtime/panic.go:617 +0x64 fp=0x1406d7d8 sp=0x1406d7c4 pc=0x42ce94
runtime.(*mcache).refill(0x2c0360, 0x18)
        C:/go/src/runtime/mcache.go:137 +0xec fp=0x1406d7e8 sp=0x1406d7d8 pc=0x41518c
runtime.(*mcache).nextFree(0x2c0360, 0x18, 0x2ff, 0x8, 0x8)
        C:/go/src/runtime/malloc.go:786 +0x7a fp=0x1406d804 sp=0x1406d7e8 pc=0x40b28a
runtime.mallocgc(0xb0, 0x1182b00, 0xc9aae901, 0x2c0360)
        C:/go/src/runtime/malloc.go:939 +0x5c3 fp=0x1406d858 sp=0x1406d804 pc=0x40b9f3
runtime.newobject(...)
        C:/go/src/runtime/malloc.go:1068
runtime.mapassign_faststr(0x10ecbe0, 0x7fbff0e0, 0x7fbfc280, 0x3, 0x1)
        C:/go/src/runtime/map_faststr.go:220 +0x33c fp=0x1406d894 sp=0x1406d858 pc=0x4119cc
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.XMLToStruct(0x57dd5e60, 0x7fbff060, 0x7fbfc278, 0x8, 0x77da8970)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:83 +0x392 fp=0x1406d970 sp=0x1406d894 pc=0xcff132
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.XMLToStruct(0x57dd5e60, 0x7f8cf940, 0x7f8b3d10, 0x10, 0x1f33740)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:71 +0x28b fp=0x1406da4c sp=0x1406d970 pc=0xcff02b
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.XMLToStruct(0x57dd5e60, 0x0, 0x43f88f, 0x1000, 0x10dd1c0)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go:71 +0x28b fp=0x1406db28 sp=0x1406da4c pc=0xcff02b
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil.UnmarshalXML(0x1259e20, 0x757fe4c0, 0x57dd5e60, 0x0, 0x0, 0x1, 0x0)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/unmarshal.go:39 +0x30 fp=0x1406dba0 sp=0x1406db28 pc=0xcfc6c0
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/restxml.Unmarshal(0x75301440)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/private/protocol/restxml/restxml.go:56 +0xe7 fp=0x1406dbf0 sp=0x1406dba0 pc=0xd20aa7
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0x7530153c, 0x75301440)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:261 +0x67 fp=0x1406dc38 sp=0x1406dbf0 pc=0xcd4d77
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0x75301440, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:544 +0xe7 fp=0x1406dc78 sp=0x1406dc38 pc=0xcd74a7
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0x75301440, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:485 +0xf1 fp=0x1406dcc0 sp=0x1406dc78 pc=0xcd7011
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsWithContext(0x140360d0, 0x150e5c0, 0x13c1e0c8, 0x757ed100, 0x0, 0x0, 0x0, 0x1d5, 0x1d5, 0x7)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4470 +0x10e fp=0x1406dce8 sp=0x1406dcc0 pc=0xd3011e
github.com/rclone/rclone/backend/s3.(*Fs).list.func1(0x1, 0x117d201, 0x151e0c0)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1229 +0x69 fp=0x1406dd20 sp=0x1406dce8 pc=0xdc5ee9
github.com/rclone/rclone/fs.pacerInvoker(0x1, 0xa, 0x757ed120, 0x6a363730, 0x45bb7f, 0x13fc6f14)
        C:/gopath/src/github.com/rclone/rclone/fs/fs.go:1369 +0x21 fp=0x1406dd74 sp=0x1406dd20 pc=0x6d1321
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0x13fc6f00, 0x757ed120, 0xa, 0x20, 0x11d89a0)
        C:/gopath/src/github.com/rclone/rclone/lib/pacer/pacer.go:197 +0x71 fp=0x1406dda0 sp=0x1406dd74 pc=0x6bf921
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0x13fc6f00, 0x757ed120, 0x757ed0c0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/lib/pacer/pacer.go:216 +0x5d fp=0x1406ddc0 sp=0x1406dda0 pc=0x6bf9ed
github.com/rclone/rclone/backend/s3.(*Fs).list(0x140160c0, 0x150e5c0, 0x13c1e0c8, 0x13cda020, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1228 +0x5ea fp=0x1406de9c sp=0x1406ddc0 pc=0xdc03ea
github.com/rclone/rclone/backend/s3.(*Fs).listDir(0x140160c0, 0x150e5c0, 0x13c1e0c8, 0x13cda020, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1331 +0xd5 fp=0x1406ded8 sp=0x1406de9c pc=0xdc0f45
github.com/rclone/rclone/backend/s3.(*Fs).List(0x140160c0, 0x150e5c0, 0x13c1e0c8, 0x0, 0x0, 0x1, 0x13dca000, 0x13306cc, 0x2, 0x13dca000)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1386 +0xfc fp=0x1406df18 sp=0x1406ded8 pc=0xdc153c
github.com/rclone/rclone/fs/list.DirSorted(0x150e5c0, 0x13c1e0c8, 0x151e080, 0x140160c0, 0x451200, 0x0, 0x0, 0x42be3b, 0x4, 0x13cc83a0, ...)
        C:/gopath/src/github.com/rclone/rclone/fs/list/list.go:24 +0x49 fp=0x1406df6c sp=0x1406df18 pc=0x835c99
github.com/rclone/rclone/fs/march.(*March).makeListDir.func1(0x0, 0x0, 0x13ce2010, 0x0, 0x1, 0x13f8c2a0, 0x13f8c2a0)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:76 +0x4f fp=0x1406dfa0 sp=0x1406df6c pc=0x89098f
github.com/rclone/rclone/fs/march.(*March).processJob.func1(0x13ce2010, 0x13fc7780, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, 0x0, 0x13cdc040, ...)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:376 +0x55 fp=0x1406dfc0 sp=0x1406dfa0 pc=0x8910f5
runtime.goexit()
        C:/go/src/runtime/asm_386.s:1321 +0x1 fp=0x1406dfc4 sp=0x1406dfc0 pc=0x455831
created by github.com/rclone/rclone/fs/march.(*March).processJob
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:374 +0xf3b

goroutine 1 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0x13ff5938)
        C:/go/src/runtime/sema.go:56 +0x2e
sync.(*WaitGroup).Wait(0x13ff5930)
        C:/go/src/sync/waitgroup.go:130 +0x7d
github.com/rclone/rclone/fs/march.(*March).Run(0x13fc7780, 0x13fc7780, 0x127b920)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:194 +0x205
github.com/rclone/rclone/fs/operations.CheckFn(0x150e5c0, 0x13c1e0c8, 0x151e080, 0x14016180, 0x151e080, 0x140160c0, 0x132f56c, 0x0, 0x13ff1a70, 0x13c8a280)
        C:/gopath/src/github.com/rclone/rclone/fs/operations/operations.go:804 +0x143
github.com/rclone/rclone/fs/operations.Check(...)
        C:/gopath/src/github.com/rclone/rclone/fs/operations/operations.go:828
github.com/rclone/rclone/cmd/check.glob..func1.1(0x13f8d500, 0x0)
        C:/gopath/src/github.com/rclone/rclone/cmd/check/check.go:50 +0xbb
github.com/rclone/rclone/cmd.Run(0x13fb0000, 0xfb3760, 0x140a2ea8)
        C:/gopath/src/github.com/rclone/rclone/cmd/cmd.go:234 +0xbe
github.com/rclone/rclone/cmd/check.glob..func1(0xfb3760, 0x13fb8370, 0x2, 0x2)
        C:/gopath/src/github.com/rclone/rclone/cmd/check/check.go:46 +0xc3
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0xfb3760, 0x13fb8300, 0x2, 0x2, 0xfb3760, 0x13fb8300)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:830 +0x1f1
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xfb2d60, 0x5e564466, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:914 +0x252
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:864
github.com/rclone/rclone/cmd.Main()
        C:/gopath/src/github.com/rclone/rclone/cmd/cmd.go:499 +0xad
main.main()
        C:/gopath/src/github.com/rclone/rclone/rclone.go:13 +0x17

goroutine 6 [syscall, 8 minutes]:
os/signal.signal_recv(0x0)
        C:/go/src/runtime/sigqueue.go:139 +0x12f
os/signal.loop()
        C:/go/src/os/signal/signal_unix.go:23 +0x1a
created by os/signal.init.0
        C:/go/src/os/signal/signal_unix.go:29 +0x37

goroutine 8 [select]:
github.com/rclone/rclone/vendor/go.opencensus.io/stats/view.(*worker).start(0x13daf780)
        C:/gopath/src/github.com/rclone/rclone/vendor/go.opencensus.io/stats/view/worker.go:154 +0xd1
created by github.com/rclone/rclone/vendor/go.opencensus.io/stats/view.init.0
        C:/gopath/src/github.com/rclone/rclone/vendor/go.opencensus.io/stats/view/worker.go:32 +0x47

goroutine 10 [select, 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:141 +0x105
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 11 [select, 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:141 +0x105
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 12 [select, 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:141 +0x105
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 13 [select, 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:141 +0x105
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 14 [select, 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:141 +0x105
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 15 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0x13ce2018)
        C:/go/src/runtime/sema.go:56 +0x2e
sync.(*WaitGroup).Wait(0x13ce2010)
        C:/go/src/sync/waitgroup.go:130 +0x7d
github.com/rclone/rclone/fs/march.(*March).processJob(0x13fc7780, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:388 +0xd6
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:148 +0x159
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 16 [select, 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:141 +0x105
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 18 [select, 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func1(0x13ff5920, 0x13fc7780, 0x13fc77c0, 0x13ff5910, 0x14036338, 0x13ff5918, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:141 +0x105
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:138 +0x150

goroutine 19 [chan receive (nil chan), 8 minutes]:
github.com/rclone/rclone/fs/march.(*March).Run.func2(0x13fc7780, 0x13fc77c0, 0x13ff5930)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:189 +0x3a
created by github.com/rclone/rclone/fs/march.(*March).Run
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:187 +0x1f9

goroutine 35 [runnable]:
net/http.(*persistConn).roundTrip(0x140f0000, 0x7f90d7c0, 0x0, 0x0, 0x0)
        C:/go/src/net/http/transport.go:2174 +0x650
net/http.(*Transport).roundTrip(0x13c56790, 0x7b8f8e80, 0x12a9cd3, 0xa, 0x7f8dc258)
        C:/go/src/net/http/transport.go:481 +0x810
net/http.(*Transport).RoundTrip(...)
        C:/go/src/net/http/roundtrip.go:17
github.com/rclone/rclone/fs/fshttp.(*Transport).RoundTrip(0x1401e640, 0x7b8f8e80, 0x1401e640, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/fs/fshttp/http.go:330 +0x190
net/http.send(0x7b8f8e80, 0x14fe0a0, 0x1401e640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x28, 0x0, ...)
        C:/go/src/net/http/client.go:250 +0x3df
net/http.(*Client).send(0x1401ecc0, 0x7b8f8e80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x7f8dc370, 0x7f8dc370, ...)
        C:/go/src/net/http/client.go:174 +0xab
net/http.(*Client).do(0x1401ecc0, 0x7b8f8e80, 0x0, 0x0, 0x0)
        C:/go/src/net/http/client.go:641 +0x24c
net/http.(*Client).Do(...)
        C:/go/src/net/http/client.go:509
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/corehandlers.sendFollowRedirects(0x7f542240, 0x132f6d4, 0x7b8f8e00, 0x7f542240)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:120 +0x2f
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/corehandlers.glob..func3(0x7f542240)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:112 +0x60
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0x7f54231c, 0x7f542240)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:261 +0x67
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0x7f542240, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:526 +0x89
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0x7f542240, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:485 +0xf1
github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsWithContext(0x14036308, 0x150e5c0, 0x13c1e0c8, 0x7f90d440, 0x0, 0x0, 0x0, 0x1fe, 0x1fe, 0x7)
        C:/gopath/src/github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4470 +0x10e
github.com/rclone/rclone/backend/s3.(*Fs).list.func1(0x1, 0x117d201, 0x151e0c0)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1229 +0x69
github.com/rclone/rclone/fs.pacerInvoker(0x1, 0xa, 0x7f90d460, 0x723aa8e8, 0x45bb7f, 0x13fc7754)
        C:/gopath/src/github.com/rclone/rclone/fs/fs.go:1369 +0x21
github.com/rclone/rclone/lib/pacer.(*Pacer).call(0x13fc7740, 0x7f90d460, 0xa, 0x20, 0x11d89a0)
        C:/gopath/src/github.com/rclone/rclone/lib/pacer/pacer.go:197 +0x71
github.com/rclone/rclone/lib/pacer.(*Pacer).Call(0x13fc7740, 0x7f90d460, 0x7f90d400, 0x0)
        C:/gopath/src/github.com/rclone/rclone/lib/pacer/pacer.go:216 +0x5d
github.com/rclone/rclone/backend/s3.(*Fs).list(0x14016180, 0x150e5c0, 0x13c1e0c8, 0x13cd2020, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1228 +0x5ea
github.com/rclone/rclone/backend/s3.(*Fs).listDir(0x14016180, 0x150e5c0, 0x13c1e0c8, 0x13cd2020, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1331 +0xd5
github.com/rclone/rclone/backend/s3.(*Fs).List(0x14016180, 0x150e5c0, 0x13c1e0c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/backend/s3/s3.go:1386 +0xfc
github.com/rclone/rclone/fs/list.DirSorted(0x150e5c0, 0x13c1e0c8, 0x151e080, 0x14016180, 0x0, 0x0, 0x0, 0x42be3b, 0x4, 0x13cd41c0, ...)
        C:/gopath/src/github.com/rclone/rclone/fs/list/list.go:24 +0x49
github.com/rclone/rclone/fs/march.(*March).makeListDir.func1(0x0, 0x0, 0x13ce2010, 0x0, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:76 +0x4f
github.com/rclone/rclone/fs/march.(*March).processJob.func2(0x13ce2010, 0x13fc7780, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, 0x0, 0x13cdc050, ...)
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:383 +0x55
created by github.com/rclone/rclone/fs/march.(*March).processJob
        C:/gopath/src/github.com/rclone/rclone/fs/march/march.go:381 +0xeca

goroutine 58 [select]:
net/http.(*persistConn).readLoop(0x140f0000)
        C:/go/src/net/http/transport.go:1798 +0x855
created by net/http.(*Transport).dialConn
        C:/go/src/net/http/transport.go:1357 +0x8ea

goroutine 61 [select]:
net/http.(*persistConn).writeLoop(0x140c4000)
        C:/go/src/net/http/transport.go:1958 +0xcc
created by net/http.(*Transport).dialConn
        C:/go/src/net/http/transport.go:1358 +0x90b

goroutine 59 [select]:
net/http.(*persistConn).writeLoop(0x140f0000)
        C:/go/src/net/http/transport.go:1958 +0xcc
created by net/http.(*Transport).dialConn
        C:/go/src/net/http/transport.go:1358 +0x90b

goroutine 60 [select]:

**Comment by yadu-boss** [comment]
Help me to solve the issue.
